### ISSUE TITLE
WebDaveSession.cs - line 31

### ISSUE THREAD

**Issue by tmoore82** [ringostarr80/WebDav.NET#1]
I'm trying to implement your library, as I've had no success building my own connection. But every time I run your "more practical example", at `folder.Open(path)`, I get the error ""WebDav.Client.Exceptions.UnauthorizedException." It comes up no matter what credentials I use. Any suggestions?

**Comment by ringostarr80** [comment]
Hello tmoore82,

Can you give me some more informations, please.
Do you have an own webdav server or do you use a webdav provider like gmx, strato or microsoft skydrive?
Do you use Visual Studio on Windows or Mono on Linux to implement this library?

I've also tried a request on my gmx-account, but I get another Exception: "The authentication or decryption has failed."

If you have an own webdav server, can you tell me what authentication mode do you have for your webdav!?
I've only implemented the basic authentication, yet.

**Comment by tmoore82** [comment]
Thanks for getting back to me. I think the issue may be the authentication.
I'm trying to use FBA. I wasn't able to connect without using a library
that another one of our developers built from a lot of the functions found
in the WebStore Explore app:
http://code.msdn.microsoft.com/WebStoreExplore-WebDAV-012720F3. I haven't
been able to figure out why it works, yet, but I'm hoping to have some time
to look at it over the next week or so.

On Fri, Aug 23, 2013 at 9:56 AM, Ringo Leese notifications@github.comwrote:

> Hello tmoore82,
> 
> Can you give me some more informations, please.
> Do you have an own webdav server or do you use a webdav provider like gmx,
> strato or microsoft skydrive?
> Do you use Visual Studio on Windows or Mono on Linux to implement this
> library?
> 
> I've also tried a request on my gmx-account, but I get another Exception:
> "The authentication or decryption has failed."
> 
> If you have an own webdav server, can you tell me what authentication mode
> do you have for your webdav!?
> I've only implemented the basic authentication, yet.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ringostarr80/WebDav.NET/issues/1#issuecomment-23165043
> .

## 

Mr. Tyler N. Moore
moore.tyler.n@gmail.com
tmoore82.wordpress.com
(931) 216.8283
