### ISSUE TITLE
response and upload

### ISSUE THREAD

**Issue by monstress2** [ringostarr80/WebDav.NET#3]
I)WebDavFolder.ProcessResponse line 4:
XmlNodeList XmlResponseList = XmlDoc.GetElementsByTagName("D:response");
at RFC 2518 in examples used d: and D:
//I try with server https://debdav.yandex.ru and that used lowercase variant(d:response) 

II)WebDavResource.Upload without authentification

III)WebDavFolder.ProcessResponse creating children without _credentials -> method .Delete, work with empty credentials.

**Comment by ringostarr80** [comment]
Hello monstress2,

Thanks for your advice, I've fixed problem I) and II).

I don't understand the third problem, can you explain it a little bit more, please!
If the .Delete method works with empty credentials, then it's a server problem, I think!?

**Comment by monstress2** [comment]
Hello.
Your code "WebDavFolder.ProcessResponse" is creating children without _credentials(from it parent). So method .Delete use default value for credentials (see your WebDavHierarchyItem: 
protected ICredentials _credentials = new NetworkCredential(); 
). So server throw error.

I think need add line below 8 (I do it and it's works for me):
int counter = 0;
foreach(XmlNode XmlCurrentResponse in XmlResponseList) {
WebDavHierarchyItem item = new WebDavHierarchyItem();

---NEED ADD THAT--->item.SetCredentials(this._credentials);

foreach(XmlNode XmlCurrentNode in XmlCurrentResponse.ChildNodes) {

Thanx. Sorry for my bad English.

**Comment by monstress2** [comment]
Also, I have trouble with upload large resource (1GB and more). Upload and GetWriteStream, throw OutOfMemory.
That may resolve by using modification GetWriteStream, by adding:
webRequest.AllowWriteStreamBuffering = false;

But, with low speed connection throw Timeout connection. Adding line can resolve that (may be): 
webRequest.Timeout = System.Threading.Timeout.Infinite;

**Comment by monstress2** [comment]
Also WebDavResource.GetWriteStream. Look at line webRequest.GetRequestStream(), that establish connection, to close this connection need call webRequest.GetResponse(). But at this implemintation, we can't do it. So connections will remain, until Timeout... it worse.

**Comment by ringostarr80** [comment]
Hi monstress2,

I fixed the credentials bug and the problem with the timeout.
I've unified the overloaded WebDavResource.GetWriteStream(...) method and you can set the timeout in milliseconds or to System.Threading.Timeout.Infinite on the WebDavResource.TimeOut-property before you get the WriteStream.

On your last comment I will look later.

**Comment by ringostarr80** [comment]
in response to the problem with the remaining connections until timeout:

I've made this WebDav-library as an open source implementation of the API on the following site => http://www.webdavsystem.com/client/programming
As in comparison to the "IT Hit WebDav for .NET" API => http://doc3.webdavsystem.com/default.aspx?main=http://doc3.webdavsystem.com/ITHit.WebDAV.Client.Home.html
I can't see anything, that closes the connection of the overlying stream, after the write or read stream itself is closed.

I think it is intended, that the connection stays opened as long as the resource stays in context and is not collected by the garbage collector.

Nevertheless, I'm open for improvements and ideas!
